/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.lone64.launcher.occupationalwar.frame;

import dev.lone64.launcher.occupationalwar.Main;
import dev.lone64.launcher.occupationalwar.auth.MCAuth;
import java.awt.Color;
import java.awt.Point;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lone64dev
 */
public class MSAuthFrame extends JFrame {
    
    private Point mouseDownCompCoords;

    /**
     * Creates new form MainFrame
     */
    public MSAuthFrame() {
        this.mouseDownCompCoords = null;
        
        setIconImage();
        initComponents();
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 155));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeIcon = new javax.swing.JLabel();
        minimizeIcon = new javax.swing.JLabel();
        windowPanel = new javax.swing.JPanel();
        launcherTitle1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        authPanel = new javax.swing.JPanel();
        msAuthButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("점령전 런처 | 로그인");
        setName("MainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/close-16.png"))); // NOI18N
        closeIcon.setLabelFor(this);
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });

        minimizeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/minimize-16.png"))); // NOI18N
        minimizeIcon.setLabelFor(this);
        minimizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeIconMouseClicked(evt);
            }
        });

        windowPanel.setBackground(new Color(0, 0, 0, 0));
        windowPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowPanelMouseDragged(evt);
            }
        });
        windowPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                windowPanelMouseReleased(evt);
            }
        });

        launcherTitle1.setFont(launcherTitle1.getFont().deriveFont(launcherTitle1.getFont().getStyle() | java.awt.Font.BOLD, 12));
        launcherTitle1.setForeground(new java.awt.Color(255, 255, 255));
        launcherTitle1.setText("마인크래프트 점령전 런처");

        javax.swing.GroupLayout windowPanelLayout = new javax.swing.GroupLayout(windowPanel);
        windowPanel.setLayout(windowPanelLayout);
        windowPanelLayout.setHorizontalGroup(
            windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowPanelLayout.createSequentialGroup()
                .addComponent(launcherTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        windowPanelLayout.setVerticalGroup(
            windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowPanelLayout.createSequentialGroup()
                .addComponent(launcherTitle1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new Color(0, 0, 0, 0));

        authPanel.setBackground(new Color(0, 0, 0, 0));

        msAuthButton.setFont(msAuthButton.getFont().deriveFont(msAuthButton.getFont().getStyle() | java.awt.Font.BOLD, 14));
        msAuthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/microsoft_icon.png"))); // NOI18N
        msAuthButton.setText("마이크로소프트 로그인");
        msAuthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        msAuthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msAuthButtonMouseClicked(evt);
            }
        });

        warningLabel.setFont(warningLabel.getFont().deriveFont(warningLabel.getFont().getStyle() | java.awt.Font.BOLD, 12));
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setText("해당 런처를 사용하려면 마이크로소프트 로그인을 진행해주세요.");

        javax.swing.GroupLayout authPanelLayout = new javax.swing.GroupLayout(authPanel);
        authPanel.setLayout(authPanelLayout);
        authPanelLayout.setHorizontalGroup(
            authPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
            .addGroup(authPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(msAuthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        authPanelLayout.setVerticalGroup(
            authPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msAuthButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(warningLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(authPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(windowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimizeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void minimizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeIconMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeIconMouseClicked

    /* Window Controller */
    private void windowPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMouseDragged
        var currCoords = evt.getLocationOnScreen();
        setLocation(currCoords.x - this.mouseDownCompCoords.x, currCoords.y - this.mouseDownCompCoords.y);
    }//GEN-LAST:event_windowPanelMouseDragged

    private void windowPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMousePressed
        this.mouseDownCompCoords = evt.getPoint();
    }//GEN-LAST:event_windowPanelMousePressed

    private void windowPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMouseReleased
        this.mouseDownCompCoords = null;
    }//GEN-LAST:event_windowPanelMouseReleased
    /* Window Controller */
    
    private void msAuthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msAuthButtonMouseClicked
        this.msAuthButton.setEnabled(false);
        var account = MCAuth.getInstance().loginAccount();
        if (account == null) {
            this.msAuthButton.setEnabled(true);
            System.out.print("[%s] An error occurred while logging in to Microsoft.".formatted(Main.LAUNCHER_NAME));
            JOptionPane.showMessageDialog(this, "마이크로소프트 로그인 도중 오류가 발생했습니다.", Main.LAUNCHER_NAME, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        setVisible(false);
        MainFrame.visible(account);
    }//GEN-LAST:event_msAuthButtonMouseClicked

    private void setIconImage() {
        URL imgURL = Main.class.getResource("/assets/icon/app_icon.png");
        ImageIcon icon = new ImageIcon(imgURL);
        setIconImage(icon.getImage());
    }
    
    public static void visible() {
        var frame = new MSAuthFrame();
        frame.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authPanel;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel launcherTitle1;
    private javax.swing.JLabel minimizeIcon;
    private javax.swing.JButton msAuthButton;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables

}